### ISSUE TITLE
installation notes: quicklook etc.

### ISSUE THREAD

**Issue by timjph** [mz2/imotifs#2]
Might be better to put the quicklook installation notes with notes on the dmg installation

Installation currently points to 0.22 not 0.24, however 0.24 dmg does not seem to exist

Worth pointing out in Installation notes that there is an example file.

Question: If you do an update of imotifs which includes adding a new example file in the dmg, what happens?  i.e. if you improve the associated files, is it necessary to force existing users to install again from dmg to get extra files?

**Comment by mz2** [comment]
People won't get new files without downloading the DMG manually. I could put links to the new files in the release notes that get seen upon launch, but this might not reach too many people.

Combination of release notes and links on the wiki are probably the best way to do this.

**Comment by mz2** [comment]
Moved QuickLook plugin installation instructions to the main page from the Getting Started guide.
